M48
; DRILL file KiCad 10.0.5 date 2026-09-30T20:41:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T20:41:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.190
%
G90
G05
T1
X101.19Y-42.76
X101.19Y-73.24
X108.81Y-42.76
X108.81Y-73.24
T2
X105.0Y-43.27
X105.0Y-72.73
M30
